### PR TITLE
[GH-240]:Fixed issue #240 edited the pretext of custom post

### PR DESCRIPTION
**Pull request by Kshitij-Katiyar**
**Summary** 

- Users could not edit the post's pretext message for starting a new zoom meeting due to a hardcoded message.
- This PR contains all the changes from [Pr #248](https://github.com/mattermost/mattermost-plugin-zoom/pull/248) So this PR alone is enough to fix this issue so we can close [Pr #248](https://github.com/mattermost/mattermost-plugin-zoom/pull/248) afterward.

**Issue** 

- Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/240
- [Pr #248](https://github.com/mattermost/mattermost-plugin-zoom/pull/248)

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by mickmister — APPROVED** [review]

**Comment by Kshitij-Katiyar** [comment]
> /update-branch

@hanzei synced with master

**Comment by hanzei** [comment]
@AayushChaudhary0001 Can you please review this PR?

**Review by AayushChaudhary0001 — COMMENTED** [review]
@hanzei @Kshitij-Katiyar  Tested this PR, working fine for text messages, but not supporting emoji's and GiF's if added in the message
image

image

**Comment by mickmister** [comment]
To render the markdown using the webapp's markdown logic, we can use the webapp's exposed functions [formatText](https://developers.mattermost.com/integrate/plugins/components/webapp/reference/#formattexttext-options) and [messageHtmlToComponent](https://developers.mattermost.com/integrate/plugins/components/webapp/reference/#messagehtmltocomponenthtml-isrhs-options)

https://github.com/mattermost/mattermost-plugin-ai/blob/6f5c45ccbf3bb262fb6710bdc6a08838ff47e5cc/webapp/src/components/post_text.tsx#L43-L47

```js
    const text = messageHtmlToComponent(
        formatText(props.message, markdownOptions),
        true,
        messageHtmlToComponentOptions,
    );

    return (
        <div>
            {text}
        </div>
    );
```

**Comment by avas27JTG** [comment]
> @hanzei @Kshitij-Katiyar Tested this PR, working fine for text messages, but not supporting emoji's and GiF's if added in the message image
> 
> image

@AayushChaudhary0001 this has been fixed.

**Pull request merged**
