### PR TITLE
Add icon

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Screenshot from 2020-04-01 07-26-54

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/94

### CODE REVIEW

**Comment by DHaussermann** [comment]
@hanzei This may be a silly question but, is this change actually testable before a PR is made to the marketplace repo to include a version with this change? 

I have deployed this locally and don't see the icon for the market place (including fresh cache) The webpp is still serving me the old svg. The new .svg is visible in the file system once deployed.

**Comment by hanzei** [comment]
@DHaussermann Yes, this changes should be visible in the marketplace modal when deploying the plugin.

Steps:
1. Start Mattermost server with `master` of `server` and `webapp`
2. Deploy plugin from this branch
3. Open Marketplace Modal
4. Observe Zoom icon next to `Zoom (1.2.0)`

Can you confirm that these steps work?

**Comment by DHaussermann** [comment]
@hanzei No. These steps do not work for me to see the new icon in the marketplace.
I still see the generic icon after following these steps. 
- I have also tried re-opening the marketplace in incognito browser
- I have confirmed that that the .tg package I'm uploading contains the Zoom.svg in the assets folder
I'm not sure what could be going on.     
Note that the production plugin marketplace already contains a `v1.3.0.` and this branch will also build as `v1.3.0.` Perhaps the modal does not refresh as it looks like nothing new is available?

**Comment by hanzei** [comment]
Good catch @DHaussermann. Would you disable `Enable Remote Marketplace`?
Screenshot from 2020-04-17 10-04-57

**Comment by DHaussermann** [comment]
Thanks @hanzei disabling this in the config does allow me to test the change!

**Pull request merged**
