### PR TITLE
Save state when using connect on Account level oauth

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Save state when using connect command on Account level oauth

#### Ticket Link
None

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Review by jfrerich — APPROVED** [review]

**Comment by hanzei** [comment]
@larkox Should that change go into 1.5?

**Comment by DHaussermann** [comment]
@hanzei  Yes it is needed. I will regression test the authentication now.

**Comment by DHaussermann** [comment]
Tested and passed
- Regression tested User level oAuth and Account level oAuth
- Tested across multiple browser session states including those with fresh cache and those that had been previously authenticated with a different set of Google OAuth credentials
- It is possible that the user will need to change the credentials they are using to correspond with Zoom when they are Authorizing the app (as expected)
- That said, in all cases In never reproduced the issue of the invalid session state   

LGTM!

**Review by DHaussermann — APPROVED** [review]

**Comment by DHaussermann** [comment]
@hanzei please merge if you are available. 
Also I am slightly confused. This PR is also needed in the cloud release branch as per a discussion with @larkox  earlierbut this was forked from master. Is a cherry-pick needed?

**Comment by hanzei** [comment]
@DHaussermann Exactly. I just cherry-picked the changes into `release_v1.5.0-cloud`.

**Pull request merged**
