### PR TITLE
Add autocomplete icon

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Screenshot from 2020-09-15 11-53-30
Screenshot from 2020-09-15 11-53-42

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/164

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by asaadmahmood — APPROVED** [review]

**Comment by hanzei** [comment]
@larkox I dismissed your review accidentally

**Review by larkox — APPROVED** [review]

**Review by jfrerich — APPROVED** [review]
Beautiful :)

**Comment by hanzei** [comment]
@larkox @jfrerich I'm wondering if one of you is open on doing a dev QA review on this PR?

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Autocomplete icon is displayed as expected

LGTM!


Found some type of lint error but it was unrelated to this PR. Created https://github.com/mattermost/mattermost-plugin-zoom/issues/168 to address this.

**Pull request merged**
