### PR TITLE
Updated API Key/Secret requirements

### PR DESCRIPTION
**Pull request by faase**
#### Summary
In the read.me the line 'To generate an API Key and API Secret requires a Pro, Business, Education, or API Zoom plan.' was wrong. A user reported that they were still able to generate the API Key and API Secret even though they were on the Basic plan, though the Zoom plugin still wouldn't work as it's not one of the plans listed. 

#### Ticket Link
I was made aware of this issue in char so there is no ticket number. This comment mentions it however https://github.com/mattermost/mattermost-plugin-zoom/issues/43#issuecomment-541661239 .

### CODE REVIEW

**Comment by larkox** [comment]
Closing this since all documentation will be handled on GitBook.
(The contents will be taken in mind for updating the documentation in GitBook)

**Comment by jasonblais** [comment]
Why not fix a bug in docs vs wait until it's published to the GitBook?

**Comment by larkox** [comment]
Because the docs will be "fixed" having a link to he gitbook. I thought I already submitted the PR to update the README. It is the PR #126

**Comment by jasonblais** [comment]
I see, didn't realize it was already published in GitBook

**Pull request closed without merging**
