### PR TITLE
Release v1.5.0

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
I used `pluginops release` to cut the release. That added all of the default values. I'm 1/5 that this makes the file more readable. 

#### Ticket Link
Part of https://github.com/mattermost/mattermost-plugin-zoom/issues/182

### CODE REVIEW

**Review by larkox — APPROVED** [review]
LGTM. The missing fields seem a bit of an overkill, but as long as it does not introduce any issue, I am fine with it.

**Comment by DHaussermann** [comment]
@larkox I have done a round of release testing on this and found no functional issues. However `Enable OAuth` should no longer show as `Beta` 

Can you please resolve this here https://github.com/mattermost/mattermost-plugin-zoom/issues/201 before we create a On-Prem 1.5release?

**Comment by hanzei** [comment]
Sure, submitted https://github.com/mattermost/mattermost-plugin-zoom/pull/202.

**Comment by hanzei** [comment]
@DHaussermann Heads up that I pushed some open PRs into this release. It made little sense to me to release 1.5.0 and then 1.5.0 shortly after. You can find the list at https://github.com/mattermost/mattermost-plugin-zoom/issues/182.

**Comment by DHaussermann** [comment]
@hanzei yes, this is an odd situation as we have already shipped the cloud release for 1.5.0 The idea @aaronrothschild and I had was to ship 1.5.0 for on-prem before we make too many more changes so we don't have significantly different version both labeled 1.5.0 

Once we have 1.5.0 On-Prem released, the code change to remove JWT can be merged to master and we can move forward with the same code branch again for both Cloud and On-Prem. 

Do you have any thoughts on this? For https://github.com/mattermost/mattermost-plugin-zoom/pull/197 and https://github.com/mattermost/mattermost-plugin-zoom/pull/198 is it simpler to just include them in the 1.5.0 on-prem release?

**Comment by hanzei** [comment]
Yes, I think that #197 and #198 are simple fixes that should go into 1.5.0. They shouldn't take long to review and merge. The code has already diverged from 1.5.0-cloud and hence I don't think it's a big deal to also include these changes.

**Comment by hanzei** [comment]
@DHaussermann Heads up that this release is ready for review

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Reviewed PRs since 1.4.0 and ensured release test are current and include  Account Level oAuth
- Regression tested JWT and tested User level oAuth and Account level oAuth
- Ran through release testing for other regression tests 
- No issues found 
- Version correctly set as `1.5.0`

LGTM!

**Pull request merged**
