### PR TITLE
Bump version v1.7.0.

### PR DESCRIPTION
**Pull request by avas27JTG**
#### Summary

- https://github.com/mattermost/mattermost-plugin-zoom/pull/284
- https://github.com/mattermost/mattermost-plugin-zoom/pull/299
- https://github.com/mattermost/mattermost-plugin-zoom/pull/308
- https://github.com/mattermost/mattermost-plugin-zoom/pull/307
- https://github.com/mattermost/mattermost-plugin-zoom/pull/287
- https://github.com/mattermost/mattermost-plugin-zoom/pull/310
- https://github.com/mattermost/mattermost-plugin-zoom/issues/311
- https://github.com/mattermost/mattermost-plugin-zoom/issues/312
- https://github.com/mattermost/mattermost-plugin-zoom/issues/313
- https://github.com/mattermost/mattermost-plugin-zoom/pull/305
- https://github.com/mattermost/mattermost-plugin-zoom/pull/251
- https://github.com/mattermost/mattermost-plugin-zoom/pull/257
- https://github.com/mattermost/mattermost-plugin-zoom/pull/147
- https://github.com/mattermost/mattermost-plugin-zoom/pull/228
- https://github.com/mattermost/mattermost-plugin-zoom/pull/209
- https://github.com/mattermost/mattermost-plugin-zoom/pull/329
- https://github.com/mattermost/mattermost-plugin-zoom/pull/325
- https://github.com/mattermost/mattermost-plugin-zoom/pull/320
- https://github.com/mattermost/mattermost-plugin-zoom/pull/326
- https://github.com/mattermost/mattermost-plugin-zoom/pull/328
- https://github.com/mattermost/mattermost-plugin-zoom/pull/327
- https://github.com/mattermost/mattermost-plugin-zoom/pull/332
- https://github.com/mattermost/mattermost-plugin-zoom/pull/330
- https://github.com/mattermost/mattermost-plugin-zoom/issues/199
- https://github.com/mattermost/mattermost-plugin-zoom/pull/339

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
The PR says it's out of date with the master branch

**Comment by arush-vashishtha** [comment]
While performing the sanity testing i found an issue related to the limit in the `Meeting topic` while creating a meeting through the slash command `/zoom start <meeting topic>` for a very long meeting topic in any desired channel or DM/GM on MM.

**Steps to reproduce:**
Run the slash command `/zoom start <meeting topic>`, with a very long meeting topic in any desired channel or DM/GM on MM.

**Expected result:**
The Zoom meeting should be created for the very long meeting topic.

**Actual result:**
Zoom meeting is not created for a very long meeting topic.

image
cc @raghavaggarwal2308 @AayushChaudhary0001

**Comment by arush-vashishtha** [comment]
This PR have been tested for all the PRs included, the basic flows and slash commands in the above mentioned list and they are working fine. Nonetheless found another issue regarding the "emojis" added to the meeting topic in the slash command `/zoom start <meeting topic>`.

**Steps to Reproduce:**
Run the slash command `/zoom start <meeting topic>` in any desired channel or DM/GM on MM and add emojis in the meeting topic.

**Expected result:**
The emoji should render properly in the meeting topic on slack attachment for the new meeting in the desired channel or DM/GM on MM.

**Actual result:**
The emoji name is being displayed in the meeting topic instead of the emoji in the desired channel or DM/GM on MM.

image

cc @raghavaggarwal2308 @AayushChaudhary0001

**Comment by raghavaggarwal2308** [comment]
> This PR have been tested for all the PRs included, the basic flows and slash commands in the above mentioned list and they are working fine. Nonetheless found another issue regarding the "emojis" added to the meeting topic in the slash command `/zoom start <meeting topic>`.
> 
> **Steps to Reproduce:** Run the slash command `/zoom start <meeting topic>` in any desired channel or DM/GM on MM and add emojis in the meeting topic.
> 
> **Expected result:** The emoji should render properly in the meeting topic on slack attachment for the new meeting in the desired channel or DM/GM on MM.
> 
> **Actual result:** The emoji name is being displayed in the meeting topic instead of the emoji in the desired channel or DM/GM on MM.
> 
> image
> 
> cc @raghavaggarwal2308 @AayushChaudhary0001

@arush-vashishtha This issue is fixed now

**Comment by arush-vashishtha** [comment]
> @arush-vashishtha I don't think this issue is related to any of the PR created in this release. Can you please create a separate issue for this? We can pick this up in an upcoming release.

A separate issue has been created, please look into it.
https://github.com/mattermost/mattermost-plugin-zoom/issues/336

**Comment by mickmister** [comment]
@raghavaggarwal2308 The PR got closed since the issue was linked in the PR description, even though it was linked to comment

CleanShot 2024-01-29 at 21 18 42

**Comment by mickmister** [comment]
@avas27JTG Heads up that the PR is currently out of date with master

**Pull request merged**
