### PR TITLE
[issue 240] zoom meeting message is not edited. #240

### LINKED ISSUE #240: zoom meeting message is not edited.
https://user-images.githubusercontent.com/89907719/141179728-505df1ec-1267-4454-97fa-e5926bece3da.mp4

### PR DESCRIPTION
**Pull request by sibasankarnayak**
rendered the post message instead of hardcoded text

ticket here

Fixes #240

### CODE REVIEW

**Review by larkox — APPROVED** [review]
LGTM, but don't we want to change it also for meeting ended? (Meeting recently created probably is fine, since it is a ephemeral message that cannot be edited.

**Comment by sibasankarnayak** [comment]
> LGTM, but don't we want to change it also for meeting ended? (Meeting recently created probably is fine, since it is a ephemeral message that cannot be edited.

@larkox sure we can do it.

**Comment by dipak-demansol** [comment]
tested with the 6.5.0, 6.4.0 & 6.3.0 mattermost version, LGTM for the 6.3 & 6.4, in the 6.5 mattermost version, With The PR build i'm not able to connect Zoom but with the same Config the Market place zoom is Working so need to discuss with dylan then i will give the Final Update.

**Comment by dipak-demansol** [comment]
may be i'm facing issue because of this https://github.com/mattermost/mattermost-plugin-zoom/pull/253, lets wait for merge that PR, then i'll test This again.

**Comment by mickmister** [comment]
@sibasankarnayak Please check the "let maintainers update my branch" checkbox when submitting PRs, if this is not already the case

**Comment by mickmister** [comment]
@dipak-demansol The issue you point out is unrelated to this PR, so I think you can approve it given your message

**Comment by dipak-demansol** [comment]
> @dipak-demansol The issue you point out is unrelated to this PR, so I think you can approve it given your message

Sure, i'll test it again on latest MM version and then i'll update here.

**Comment by dipak-demansol** [comment]
@sibasankarnayak after adding PR branch build i'm not able to connect with zoom account, getting this error as `Could not complete the connection: [Click here to link your Zoom account.](https://my-server-URL/plugins/zoom/oauth2/connect)` so i request you to add master branch latest code into this branch

**Comment by dipak-demansol** [comment]
image
getting those error on console

**Review by dipak-demansol — CHANGES_REQUESTED** [review]
I'm not able to connect the zoom account with this PR build, with the release build i'm able to connect the account. 

pls see the video :- https://user-images.githubusercontent.com/89907719/165923301-576e823a-f641-4086-b8fc-16cc2f30a002.mov

FYI as per dylan there is already a solution in other PR so best it to wait to merge that PR and then test this.

**Comment by sibasankarnayak** [comment]
> 

@dipak-demansol you mean there is a PR opened which need to be merge to master first and then i need to update the PR ?

**Comment by dipak-demansol** [comment]
> > 
> 
> @dipak-demansol you mean there is a PR opened which need to be merge to master first and then i need to update the PR ?

75% Yes, @DHaussermann pls provide the info about it.

**Comment by DHaussermann** [comment]
@sibasankarnayak There are issues still being investigated by myself and @mickmister for oAuth. That said, the issue @dipak-demansol is seeing no longer occurs for me in this branch here https://github.com/mattermost/mattermost-plugin-zoom/tree/pre-release-1.6.0_with-michael-fix 

Is there a way to unlock testing on this as the issue seems unrelated to your PR.

**Comment by sibasankarnayak** [comment]
> @sibasankarnayak There are issues still being investigated by myself and @mickmister for oAuth. That said, the issue @dipak-demansol is seeing no longer occurs for me in this branch here https://github.com/mattermost/mattermost-plugin-zoom/tree/pre-release-1.6.0_with-michael-fix
> 
> Is there a way to unlock testing on this as the issue seems unrelated to your PR.

unless and until we can not create the meeting

**Pull request closed without merging**
