### PR TITLE
 Updated the "I have ended the meeting." phrasing to "The meeting has ended." as asked in #210

### PR DESCRIPTION
**Pull request by emskaplann**
#### Summary
I updated the "I have ended the meeting." phrasing to "The meeting has ended." as asked in #210.

#### Ticket Link
https://github.com/mattermost/mattermost-plugin-zoom/issues/210

### CODE REVIEW

**Review by larkox — APPROVED** [review]
LGTM :tada:. Thank you very much for your contribution!

**Review by mickmister — APPROVED** [review]
LGTM :+1: Thanks @emskaplann!!

**Review by DHaussermann — COMMENTED** [review]
Tested and passed
- New text shows "The meeting has ended" as expected
- I don't see much risk of any functional change but I did briefly regression test basic functionality asa precaution.
- No issues found

LGTM!

**Review by DHaussermann — APPROVED** [review]
Thanks @emskaplann for this enhancement!

**Pull request merged**
