### PR TITLE
Bump version to 1.4.1

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Bump version to v1.4.1

Proposal to bump fix version to prep for release using the following Release Notes.

#### Fixes
* 11147f6 Remove "EnableLegacyAuth" from the configuration (#142)
* cb3cb85 [GH-143] Add icon as SVG for version previous to 5.24 (#144)

### CODE REVIEW

**Comment by hanzei** [comment]
@larkox Should https://github.com/mattermost/mattermost-plugin-zoom/pull/142 go into this release?

**Comment by larkox** [comment]
Yes, I was about to update the description.

**Comment by larkox** [comment]
@DHaussermann Ready for testing whenever you want.

**Comment by DHaussermann** [comment]
@aaronrothschild you have a review requested on this PR. 

Note that the only changes that are apparent to the user from `v1.4.0` is that JWT no longer has it's own true / false radio. JWT is applied when ever oAuth is false. We also fixed the icon for older server versions.

**Pull request merged**
