### PR TITLE
Change image asset name to fix `cutplugin` command

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

The asset name `zoom-plugin-configuration.png` was causing issues with the `cutplugin` command, likely because it contains the word "plugin". This PR changes the image name to avoid this conflict. 

```
Error while signing plugin
Error: failed to create platform tars: found wrong platform binary in /tmp/zoom-1.7.0.tar.gz1009784493/mattermost-plugin-zoom-v1.7.0-rc1-osx-amd64.tar.gz, expected plugin-darwin-amd64, but found [plugin-darwin-amd64 zoom-plugin-configuration.png]
```

I don't see where this file (or other files from the `assets` folder) are being used. I see links in the README like https://github.com/mattermost/mattermost-plugin-zoom/assets/74422101/3928708d-8b57-474b-9c4a-d1e21c054d31 that seem to reference images in the `assets` folder, though I don't know how to verify which file it's accessing, and I don't know if I will break anything by renaming/removing images files. I don't see the name of the file `zoom-plugin-configuration.png` (or most of the files in the `assets` folder) being used anywhere in the repo, so it seems there is nothing using it but I'm not sure.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/CLD-6689

### CODE REVIEW

**Comment by mickmister** [comment]
With regards to the image references in the README, none of them seem to be referencing the checked-in images directly. I'm going to convert the ones being used into checked-in files, and get rid of any checked-in files that are not being referenced in the repoditory.

**Comment by mickmister** [comment]
I don't want to complicate this PR though. This is meant to unblock the RC build issue

**Comment by raghavaggarwal2308** [comment]
@mickmister We have created PR against the master to fix the failing CI here. We can sync this PR once that is merged.
https://github.com/mattermost/mattermost-plugin-zoom/pull/332

**Review by avas27JTG — APPROVED** [review]

**Comment by avas27JTG** [comment]
> @mickmister We have created PR against the master to fix the failing CI here. We can sync this PR once that is merged. #332

I've done this

**Pull request merged**
