### PR TITLE
[MM-18201] Use mattermost-redux to handle csrf issues

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR upgrades mattermost-redux to use `Client4.getOptions`, in order to correctly include the csrf token.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-18201

#### QA Steps

- Set `ServiceSettings.ExperimentalStrictCSRFEnforcement` to true in the server's config.json
- Verify that you can click the zoom button to begin a meeting

### CODE REVIEW

**Comment by mickmister** [comment]
@crspeller Should we be updating `mattermost-redux` to latest (or latest release)? I set it to the current version being used in the Jira plugin here.

**Comment by mickmister** [comment]
Holding off on merge until this `mattermost-redux` PR is merged https://github.com/mattermost/mattermost-redux/pull/980 , so we can update the `mattermost-redux` dependency to latest.

**Comment by DHaussermann** [comment]
@mickmister can you provide any guidance on functional testing for this? I can regression test the functionality but I'm unsure how I can explicitly validate this.

**Comment by mickmister** [comment]
@DHaussermann Create Zoom chat should work in general. If the link is posted, that is confirmation.

If there is an error that occurs on Zoom's side, the error from Zoom should show in an ephemeral post, prefixed with `Zoom error: `. An example is if the MM email address does not match the email in Zoom.

**Comment by mickmister** [comment]
@DHaussermann I added qa steps to the description including the first step:

- Set `ServiceSettings.ExperimentalStrictCSRFEnforcement` to true in the server's config.json

**Pull request merged**
