### PR TITLE
Bump version to 1.3.1

### LINKED ISSUE #77: Release v1.3.1
https://github.com/mattermost/mattermost-plugin-zoom/pull/73 alone justifies cutting a patch release.

@levb @larkox Anything else that you want go include in the release?

### PR DESCRIPTION
**Pull request by jfrerich**
### Summary
Bump version to v1.3.1

Proposal to bump Minor Version to prep for release with the following Release Notes:

#### Enhancements 
* bbf8809 MM-22921 - Updating zoom styling for attachment (#75)

#### Fixes
* 2d706c0 [MM-22638] Fix undefined name (#73)
* 6a65211 Bump acorn from 6.2.0 to 6.4.1 in /webapp (#80)

### Ticket Link
Fixes #77 

[MM-22638]: https://mattermost.atlassian.net/browse/MM-22638

#### Outstanding PRs
- [x] #91 
- [x] #88 
- [x] #93

### CODE REVIEW

**Comment by jfrerich** [comment]
I proposed releasing without #72 and adding it with the 1.4 (oauth) release.  I don't have the mana available to resolve it right now.

https://github.com/mattermost/mattermost-plugin-zoom/issues/77#issuecomment-603933982

**Comment by larkox** [comment]
Are we in time to include a fix for this #91 ? Hopefully I can have the fix today.

**Comment by jfrerich** [comment]
@larkox, sure. I added #91 as an outstanding issue and the DNM label.

**Comment by DHaussermann** [comment]
@jfrerich  we can now cut a 1.3.1 release. In addition to the 2 issues in the description we have fixes in for https://github.com/mattermost/mattermost-plugin-zoom/pull/88 and https://github.com/mattermost/mattermost-plugin-zoom/pull/93 mentioned above.

**Pull request merged**
