### PR TITLE
[GH-304] Update logic to post meeting link in thread when a thread is open in RHS

### LINKED ISSUE #304: Meeting link getting posted in channel's main thread although a thread is open in rhs
### Steps to reproduce
- Install and setup the plugin
- Enable Collapsed Reply Thread(CRT)
- Create a thread and click on it so that it opens in the right-hand sidebar (RHS)
- Click on zoom plugin button in app bar

### Expected Behaviour
- Meeting link to be posted in the thread currently open in rhs

### Observed Behaviour
- Meeting link being posted in the channel's main thread

### Screenshots
Screenshot from 2023-09-25 18-45-54

Screenshot from 2023-09-25 18-46-03

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
Update logic to post meeting link in the thread when a thread is open in RHS

#### Screenshot
image

#### What to test?
- Meeting links are getting posted in the thread when a thread is open in the RHS.

###### Steps to reproduce:
1. Connect your Zoom account.
2. Enable Collapsed Reply Thread(CRT) from system console.
3. Create a thread in a channel and open it in RHS.
4. Click on the zoom button in the app bar/channel header.

###### Environment
MM version: v9.2.2
Node version: 14.18.0
Go version: 1.20.11

#### Ticket Link
Fixes #304

### CODE REVIEW

**Review by mickmister — APPROVED** [review]
LGTM :+1:

**Review by AayushChaudhary0001 — APPROVED** [review]
Tested and approved.
Working fine for CRT(enabled), LGTM.

**Comment by mickmister** [comment]
@raghavaggarwal2308 I think this may be an unwanted change in functionality. We fixed the "threads view" issue https://github.com/mattermost/mattermost-plugin-zoom/issues/300 in a previous PR, but I'm not sure the issue linked here https://github.com/mattermost/mattermost-plugin-zoom/issues/304 is a bug. The plugin has always worked that way, and we are now changing how it works which could cause some confusion and unexpected behavior for users.

@matthewbirtch I'd like to get your thoughts on this. If an RHS thread is open while in the center channel view (not "Threads" view), and we click the Zoom icon in the Apps Bar, should the post for the meeting be created in the center channel or in the open thread? Up until this PR, it has always posted into the center channel, but this PR changes the functionality to post in the RHS.

**Comment by matthewbirtch** [comment]
> @matthewbirtch I'd like to get your thoughts on this. If an RHS thread is open while in the center channel view (not "Threads" view), and we click the Zoom icon in the Apps Bar, should the post for the meeting be created in the center channel or in the open thread? Up until this PR, it has always posted into the center channel, but this PR changes the functionality to post in the RHS.

Posting the zoom link within the thread makes sense in the `Threads` inbox view, so we're good there. But I see your point about whether we should post the zoom link to the RHS thread while in the channel view. I was thinking that maybe we could infer where you intend to post the link based on whether the thread reply input or the channel input is focused (and default to the channel if neither is focused).

I'd like to bring @asaadmahmood in to this though. Asaad, could you help answer this and come together on a solution with @mickmister?

**Comment by mickmister** [comment]
> I was thinking that maybe we could infer where you intend to post the link based on whether the thread reply input or the channel input is focused (and default to the channel if neither is focused).

@matthewbirtch 2/5 This is outside of the scope of what plugins are responsible for. And if we did implement that, it would be a hacky/brittle solution relying on css selectors to "find" the textbox and inspect focus.

The main thing I'm concerned about, is that this change in a way causes a regression, since we are changing the behavior of the plugin here. As a user, I "know" it will post in the center channel, and I trust that the plugin will continue operating that way. Having the functionality change on me will cause meetings to be posted in the wrong channel/thread when I click the button. I'm 2/5 on keeping it how it is to maintain trust of existing users of the plugin.

**Comment by mickmister** [comment]
@matthewbirtch Yes there's a separate fix for that https://github.com/mattermost/mattermost-plugin-zoom/pull/325

@raghavaggarwal2308 @avas27JTG I'm thinking we should revert this PR (that we are commenting on here) that changes the behavior of when the center channel is visible

**Comment by matthewbirtch** [comment]
Ok, makes sense to me @mickmister

**Comment by asaadmahmood** [comment]
@matthewbirtch @mickmister So if a conversation is going on in an RHS thread from a different channel (UX Design), while the center channel is bugs.

There is no way for me to create a call for the channel in the RHS?

**Comment by mickmister** [comment]
> There is no way for me to create a call for the channel in the RHS?

@asaadmahmood You can run `/zoom start` in the RHS thread but I don't think that's widely used.

For the Apps Bar icon use case, maybe we need to ask the user where they want the meeting to be posted, but then we don't get the benefits of the "one-click" nature of the feature.

**Pull request merged**
