### PR TITLE
[MM-22047] Bump version to 1.3.0

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Bump version to 1.3.0.

~~https://github.com/mattermost/mattermost-plugin-zoom/pull/61 should be go in first.~~

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-22047

### CODE REVIEW

**Comment by levb** [comment]
I suggest we wait for https://mattermost.atlassian.net/browse/MM-22113 to be investigated, cc @larkox @cpoile

**Comment by hanzei** [comment]
@levb Given that the issue linked above will be fixed with https://github.com/mattermost/desktop/pull/1178, are you fine with releasing the plugin as it is?

**Comment by hanzei** [comment]
@aaronrothschild Are you fine cutting this release?

**Comment by jfrerich** [comment]
closing. duplicate of https://github.com/mattermost/mattermost-plugin-zoom/pull/66 which will be used.

**Pull request merged**
