### PR TITLE
Change camera icon by zoom camera icon

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Change previous camera icon to Zoom Camera Icon, to distinguish between other video conferencing plugins (or other plugins were a camera icon is meaningful).

The current view is the following:

Screenshot from 2020-04-22 13-30-01

Screenshot from 2020-04-22 13-29-10

@asaadmahmood As you can see in the second screenshot, the image is not well aligned. Not sure if this is the expected result (every plugin having an image potentially different in size) or there is already something in place to do this alignment. I know you commented on the original issue that some changes may have to be made to the webapp code, but not sure if they were exactly related to this.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/102

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@larkox Yea, I may need to adjust the css in the webapp to support both images and svgs, so we can pause on this until I submit a fix in the webapp.

**Comment by asaadmahmood** [comment]
We'll wait this PR as well, as this contains the zoom icon in the font, which we will reuse instead.
https://github.com/mattermost/mattermost-webapp/pull/5353

**Comment by asaadmahmood** [comment]
@larkox We're not going to go with that branded zoom icon for this, we will use the icon font instead: `icon-brand-zoom`.

**Comment by larkox** [comment]
Current status:
Horizontal
Screenshot from 2020-05-08 13-39-03
Vertical
Screenshot from 2020-05-08 13-41-35

**Comment by asaadmahmood** [comment]
@larkox Can I also see how it looks without it being in a dropdown?

**Comment by larkox** [comment]
Final look:
Horizontal:
Screenshot from 2020-05-12 10-47-48
Vertical:
Screenshot from 2020-05-12 10-46-36

**Comment by asaadmahmood** [comment]
Looks god.

**Pull request merged**
