### PR TITLE
Bump version to 1.4.0

### PR DESCRIPTION
**Pull request by larkox**
### Summary
Bump version to v1.4.0

Proposal to bump Minor Version to prep for release with the following Release Notes:

#### Enhancements 
* df57ce9 Adding slack attachment on messages without plugin (and mobile) (#116)
* 3d941a3 Restore OAuth (#84)

#### Fixes
* 37a1b57 Fix meeting ended webhook (#111)
* 80cb1f6 Change camera icon by zoom camera icon (#104)
* 11d75e3 Use user ID instead of bot ID to post meetings (#112)
* 32185eb [GH-99] Fix JoinURL with encrypted password (#101)
* ffe5100 Bump go dependencies and go mod tidy (#124)
* 559a616 Bump dependency audit fix (#122)
* b631197 [GH-121] Add info to Zoom OAuth UI (#125)
* e9cbe14  Store post ID when creating meeting via slash command, add some logging and set expiry time to meeting post IDs to avoid garbage in the KVStore (#134)
* 9f45447 Post the already created authmessage on failed connection when using the header icon (#138)
* 7eb5b30 Remove Disconnect command when using JWT (#133)

#### Others
* 6dbfa4d Integrate GolangCI-Lint (#115)
* 92b6619 add codecov, latest release and HW badges (#118)
* 446de94 Drop second maintainer from CODEOWNERS (#103)
* 451f80e Remove usage and setup from readme and link to GitBook (#126)
* 8e6bf49 Update .circleci/config.yml (#135)
* c6183c3 Add .npmrc file for save-exact packages (#130)

### Ticket Link
None

### CODE REVIEW

**Comment by larkox** [comment]
Added some missing commits to the Others section.

**Comment by DHaussermann** [comment]
@aaronrothschild Release testing for Zoom 1.4 has now completed. The following issues were found:
https://github.com/mattermost/mattermost-plugin-zoom/issues/128
https://github.com/mattermost/mattermost-plugin-zoom/issues/127
https://github.com/mattermost/mattermost-plugin-zoom/issues/129

Please advise on if any need to be resolved https://github.com/mattermost/mattermost-plugin-zoom/issues/128 is by far the highest impact but only affects Beta oAuth functionality.

**Comment by DHaussermann** [comment]
cc @larkox FIY ☝️

**Comment by DHaussermann** [comment]
Reviewed this again and found https://github.com/mattermost/mattermost-plugin-zoom/issues/140 @larkox can you see if you can also repro this. I'm a bit confused as I feel like you have specifically addressed this issue in the last couple weeks.

**Pull request merged**
