### PR TITLE
Release 1.6.2

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

- https://github.com/mattermost/mattermost-plugin-zoom/pull/279

### CODE REVIEW

**Comment by larkox** [comment]
Why this PR has more changes than the usual bumping of the version?

**Review by m1lt0n — APPROVED** [review]

**Review by hanzei — CHANGES_REQUESTED** [review]
https://github.com/mattermost/mattermost-plugin-zoom/pull/294 needs to be merged first.

**Review by larkox — APPROVED** [review]

**Review by hanzei — APPROVED** [review]

**Comment by mickmister** [comment]
@DHaussermann This PR is ready for QA review. Note that it essentially contains only the webhook validation fix

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Ensured webhook validation is working
- Webhook documentation is updated for new value 
- Smoke tested the plugin 
  - Start and stop a meeting
  - Use slash command as well as icon
  - End meeting and ensure the post is updated by the webhook with details
  - Collision detection is working to prevent duplicate meeting starts

An issue was found with webhook secret that is not new in this release. Created https://github.com/mattermost/mattermost-plugin-zoom/issues/296 to address it.
  
  LGTM!

**Pull request merged**
