### PR TITLE
Release 1.6.1

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This release is mainly meant to deliver these two fixes:

- https://github.com/mattermost/mattermost-plugin-zoom/pull/233
- https://github.com/mattermost/mattermost-plugin-zoom/pull/253

In order to expedite the release, we are cherry-picking each of the commits in this PR

#### Ticket Link

https://github.com/mattermost/mattermost-plugin-zoom/issues/274

### CODE REVIEW

**Review by catalintomai — APPROVED** [review]

**Review by larkox — APPROVED** [review]

**Comment by mickmister** [comment]
@DHaussermann Release branch (this PR) is now updated with https://github.com/mattermost/mattermost-plugin-zoom/pull/277

**Comment by DHaussermann** [comment]
@mickmister Now that seem to be able to create Zoom App without end point validation - I have created a new App and I'm seeing an issue.
- When I use the connection link from a session where my zoom account already has credentials saved - I get directed to the page to authorize the app but then an error occurs on the zoom side and I can't get more info
image
image
- When I try in a fresh session - I see the following instead of the authorization page
image

Can you reproduce this? It's curious that on 1 day late last week I beileved this was working but I was using a pre-existing User-level oAuth app

**Comment by mickmister** [comment]
@DHaussermann There was a PR made in the plugin one year ago https://github.com/mattermost/mattermost-plugin-zoom/pull/222 that removed the scopes in this request.

More information in that PR's description but here's an important snippet:

> Apparently due to recent changes in how Zoom handles OAuth applications it no longer accepts specifying scopes with OAuth calls. According to Zoom, scopes passed in URLs were never used but now are no longer accepted.
Here's forum discussion around the topic: https://devforum.zoom.us/t/invalid-scope-errors/52654

I'm thinking maybe your Zoom app itself is configured without any OAuth scopes. This is done in Zoom's configuration UI.

**Comment by mickmister** [comment]
@DHaussermann If the above is not the issue, then this would be another breaking change on Zoom's side

**Comment by DHaussermann** [comment]
Thanks @mickmister! Proper scopes where not configured. 
This did solve the issue. 

Webhooks still don't seem to work but that may nor matter if we're adding https://github.com/mattermost/mattermost-plugin-zoom/pull/279

**Comment by DHaussermann** [comment]
Tested and passed

After further review webhooks are working for new and exiting Zoom installs:
**Case 1**
A. Install production build and make a new oAuth App - Ensure webhokk updates are working
B. Upgrade to v1.6.1 branch and ensure webhooks continue working.
**Case 2**
On yet another fresh server with fresh Zoom App - install v1.6.1 and ensure webhooks updates the Zoom post when you end a meeting

Additionally the Zoom test cycle for `v1.6.1` is now comeplete.

If we want to ship without the webhook enhancements we're now ready to merge this and create a release.

**Comment by mickmister** [comment]
> If we want to ship without the webhook enhancements we're now ready to merge this and create a release.

@DHaussermann I think this is the right move due to Zoom's webhook validation still not being rolled out. Can you please explicitly approve the PR if you agree?

**Review by DHaussermann — APPROVED** [review]
I agree with @mickmister 
We have people waiting on this already given that the oAuth issues solutions have been outstanding for quite some time. 

As tested above webhooks are functional. In my view we should cut this release and monitor the situation with Zoom to have the webhook enhancement very soon.

**Pull request merged**
