### PR TITLE
Release v1.5.0-cloud

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Similar as in https://github.com/mattermost/mattermost-plugin-zoom/pull/184 I used `pluginops release` to cut the release. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-29148

Part of https://github.com/mattermost/mattermost-plugin-zoom/issues/183

### CODE REVIEW

**Comment by hanzei** [comment]
Adding `Do Not Merge` because https://github.com/mattermost/mattermost-plugin-zoom/pull/186 needs to get merged first.

**Review by larkox — APPROVED** [review]
LGTM. Thank you very much for handling this @hanzei

**Comment by hanzei** [comment]
@DHaussermann This is ready for review

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Ensured no JWT config accessible with this version of the plugin
- Ensured oAuth state error has been resolved
- Tested again migrating form user level oAuth to app level oAuth 
- Tested around new App level feature logic for admin and non-admin
- Regression tested the plugin - launch via icon and slash command webhooks are functional etc...

LGTM!

I will be adding the new test cases for app level oAuth to the release testing shortly.

cc @hanzei and @aaronrothschild  I believe we're  ready for a marketplace PR on this.

**Comment by DHaussermann** [comment]
On 2nd thought @hanzei we may need the non-cloud version ready as well before the marketplace PR?

I'll start looking at https://github.com/mattermost/mattermost-plugin-zoom/pull/184 now.

**Pull request merged**
