### PR TITLE
Restore OAuth

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Restore OAuth from V.1.2 and minor improvements.

#### Ticket Link
None

### CODE REVIEW

**Comment by larkox** [comment]
@jfrerich I unreverted the reverting.

**Comment by larkox** [comment]
@levb @aaronrothschild Heads up on this PR ready to merge.

**Comment by gopheros** [comment]
@levb @larkox this looks like a complete re revert of OAuth feature!, wonder what caused the revert !!

**Comment by levb** [comment]
@gopheros There was an issue with Google OAuth-based _ZOOM_ accounts and the electron desktop app. It had nothing to do with our implementation of OAuth2 to zoom (your code!). @larkox is now bringing it back.

**Comment by larkox** [comment]
I added the missing piece for the OAuth (the deauthorization). Apart of all the documentation changes (to be handled by @aaronrothschild ) this should be ready to merge.

**Comment by aaronrothschild** [comment]
@larkox and @gopheros Thanks for your work on this!

**Pull request merged**
