### PR TITLE
Hackathon : Auto change user's custom status on Zoom call

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
Since the new API was in v6, i had to migrate the dependency from v5 to v6, hence the many changes. Added two new webhook support which checks if participants joins or leaves the call. Changes the custom status of the joined/left user.

Related server changes : https://github.com/mattermost/mattermost-server/pull/20551

https://user-images.githubusercontent.com/17708702/175919060-c41a7c46-4676-4b05-b3da-5a8431d1cf6a.mp4

#### Ticket Link
None

### CODE REVIEW

**Comment by mickmister** [comment]
Awesome work Zubair! I think about how we don't have this feature whenever I join a Zoom call.

There is some existing progress on this feature here https://github.com/mattermost/mattermost-plugin-zoom/pull/234. There may be some review discussion on there that is useful for development

**Comment by gavinerr** [comment]
Is there any updates on this? as this feature is very helpful for us, hope that it will be included in the near future. Thanks

**Comment by M-ZubairAhmed** [comment]
> Is there any updates on this? as this feature is very helpful for us, hope that it will be included in the near future. Thanks

We are working on adding the functionality in the server for this https://github.com/mattermost/mattermost-server/pull/20851

**Comment by M-ZubairAhmed** [comment]
Will get back to this later when time permits

**Pull request closed without merging**
