### PR TITLE
GH-154: PMI setting command for meeting creation

### LINKED ISSUE #154: Decide whether to use PMI or not on instant meetings
After #147 is merged, you will be able to create meetings with new IDs.

We would like to add a user setting set by slash commands (`/zoom setting usePMI [true/false/ask]`) to allow the user decide whether to use its PMI on instant meetings.

If the setting is set to ask, when it is going to create a meeting, they will receive an ephemeral message where they can choose to use the PMI or the new ID.

### PR DESCRIPTION
**Pull request by lantrungseo**
#### Summary

This PR support `/zoom setting usePMI [true|false|ask]` so user can choose to use their PMI or new ID to create new meeting in zoom.

+ `ask`: For each `/zoom start`, there will be ephemeral message to user to pick between 2 aforementioned optiions.
+ `true`: Dictate user to use PMI to create meeting
+ `false`: Dictate user to create meeting with new ID
#### Ticket Link
  Fixes #154

### CODE REVIEW

**Comment by lantrungseo** [comment]
@larkox I have a question: How can we send ephemeral post to user using postTypeZoom component? I tried but plugin.SendEphemeralPost(userID, post) doesn't render anything except Message. Or do I need to use other methods?

**Comment by larkox** [comment]
@lantrungseo the `Type` property of the Post will be rewritten to "ephemeral", so you want to pass the type into the post props. You can see an example in the postConfirm function implementation.

**Comment by lantrungseo** [comment]
@larkox here is my code

```
p.API.SendEphemeralPost(userId, &model.Post{
	ChannelId: channelId,
	UserId: p.botUserID,
	Message: "Would you like to create a meeting with your PMI?",
	Type: "custom_zoom",
	Props: map[string]interface{}{
		"type": "custom_zoom",
		"task": "setting/use_PMI",
	},
})
```

Below is the result.

mattermost-zoom-plugin

**Comment by larkox** [comment]
That should do the trick. Have you updated the custom type files in the plugin webapp code to handle your version?

**Comment by lantrungseo** [comment]
mattermost_zoom_post_type_errro

This is the code in the `post_type_zoom.jsx`

**Comment by lantrungseo** [comment]
Please note that I have merged branch `larkox:mattermost-plugin-zoom/CreateMeeting` ( #147) into this PR to test the whole flow.

**Comment by larkox** [comment]
@lantrungseo Thank you very much for the contribution. If you don't mind, I would like to wait for #147 to be merged into master and then master merged into this PR before reviewing it. Thank you for your patience!

**Comment by jfrerich** [comment]
> @lantrungseo Thank you very much for the contribution. If you don't mind, I would like to wait for #147 to be merged into master and then master merged into this PR before reviewing it. Thank you for your patience!

Still waiting on this PR.  Removing `stale` label.  No actionable items yet.

**Comment by lindy65** [comment]
I've asked on https://github.com/mattermost/mattermost-plugin-zoom/pull/147 to help prioritize so this PR is no longer blocked.

**Comment by dipak-demansol** [comment]
awaiting for  https://github.com/mattermost/mattermost-plugin-zoom/pull/147

**Comment by larkox** [comment]
@lantrungseo Thank you for your patience. Now that the PR that was blocking this one is merged, would you be able to merge the changes and finish this one?

**Pull request closed without merging**
